config/routes.rb
Rails.application.routes.draw do

  root "posts#index", as: "home"

  get "main" => "pages#main"
  get "main" => "pages#sub"

  resources :subscribers

resources :posts do
  resources :comments
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments, dependent: :destroy
    validates :title, presence: true, length: {minimum: 5, maximum: 255}
    validates :body, presence: true, length: {minimum: 10}
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  private def comment_params
    params.require(:comment).permit(:username, :body);
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def main

  end
  def sub

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "admin", except: [:index, :show]


  def index
    @post = Post.all
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])

    @post.destroy
    redirect_to posts_path
  end

  def update
    #render plain: params[:post].inspect

    @post = Post.find(params[:id])

    if(@post.update(post_params))
      redirect_to @post
    else
      render "edit"
    end
  end

  def create
    @post = Post.new(post_params)

    if(@post.save)
      redirect_to @post
    else
      render "new"
    end
  end

  private def post_params
    params.require(:post).permit(:title, :body, :image)
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController

  def new
    @subscriber = Subscriber.new(params[:subscriber])
    @subscriber.save
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogRuby</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag asset_path('favicon.png') %>
    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css' %>
    <%= javascript_include_tag    'https://kit.fontawesome.com/4a2aba15ee.js' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
          <i class="fas fa-guitar logo-xx"></i>
          <span class="navbar-brand"> <%= link_to "Rock Music Blog", home_path, class: "main_navig_text" %> </span>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto panel_icons">
              <li class="nav-item">
                <span class="nav-link p-2 text-light"><i class="fas fa-home logo-i"></i> <%= link_to "Main Page", home_path, class: "navig_text" %> </span>
              </li>
              <li class="nav-item">
                <span class="nav-link p-2 text-light"><i class="fas fa-list-ul logo-i"></i> <%= link_to "Categories", home_path, class: "navig_text"%> </span>
              </li>
              <li class="nav-item">
                <span class="nav-link p-2 text-light"><i class="fas fa-info logo-i"></i> <%= link_to "About", main_path, class: "navig_text" %> </span>
              </li>
              <li class="nav-item active">
                <span class="btn btn-outline-light"><i class="fas fa-plus logo-i"></i> <%= link_to "New Post", new_post_path, class: "navig_text-lst"%> </span>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      <div class="container">

      <div class="row">

        <div class="col-md-8">

          <%= yield %>

        </div>

        <div class="col-md-4 block-panel">
          <div class="card my-4">
            <h5 class="card-header">Search</h5>
            <div class="card-body">
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Search for...">
                <span class="input-group-btn">
                  <button class="btn btn-secondary" type="button">Go!</button>
                </span>
              </div>
            </div>
          </div>

          <div class="card my-4">
            <h5 class="card-header">Categories</h5>
            <div class="card-body">
                    <li>
                      <span class="p-2 text-dark"> <%= link_to "Rock & Roll News", home_path, class: "cat_text" %> </span>
                    </li>
                    <li>
                      <span class="p-2 text-dark"> <%= link_to "Rock News", home_path, class: "cat_text" %> </span>
                    </li>
                    <li>
                      <span class="p-2 text-dark"> <%= link_to "American Rock", home_path, class: "cat_text" %> </span>
                    </li>
                    <li>
                      <span class="p-2 text-dark"> <%= link_to "Rock Music News", home_path, class: "cat_text" %> </span>
                    </li>
                    <li>
                      <span class="p-2 text-dark"> <%= link_to "New Music", home_path, class: "cat_text" %> </span>
                    </li>
                    <li>
                      <span class="p-2 text-dark"> <%= link_to "Recent Post's", home_path, class: "cat_text" %> </span>
                    </li>
              </div>
            </div>

          <div class="card my-4">
            <h5 class="card-header">Subscribe Widget</h5>
            <div class="card-body">
              <form class="" action="" method="">
                <input type="email" class="form-control" placeholder="Enter Email...">
                  <span class="btn btn-primary btn-sub"><i class="fas fa-envelope logo-i"></i> <%= link_to "Subscribe", new_subscriber_path, class: "navig_text" %> </span>
              </form>
            </div>
          </div>
          <br><br><br><br><br><br>

        </div>
      </div>
    </div>



    <footer class="bg-dark">
      <div class="container">

      <div class="ftr">
        <p class="text-white"><i class="far fa-copyright"></i> RockMusicBlog 2020</p>

        <div class="social">
          <a class="btn-x" href="https://www.facebook.com/">
            <i class="fab fa-facebook"></i>
          </a>
          <a class="btn-x" href="https://twitter.com/">
            <i class="fab fa-twitter"></i>
          </a>
          <a class="btn-x" href="https://www.google.com/">
            <i class="fab fa-google"></i>
          </a>
          <a class="btn-x" href="https://www.instagram.com/">
            <i class="fab fa-instagram"></i>
          </a>
          <a class="btn-x" href="https://telegram.org/">
            <i class="fab fa-telegram"></i>
          </a>
        </div>

        <p class="text-white">All Right Reserved</p>
      </div>
    </div>
    </footer>



  </body>
</html>

app/views/pages/main.html.erb
<h1 class="my-4">About Us</h1>

<div class="card_x">
  <img class="card-img-top show_img" src="">
  <div class="card-body">
    <h2 class="card-title">Rock Music Blog - Who we are?</h2>
    <p class="card-text">We are just a team of bloggers, programmers and just rock and roll fans.<br>In our blog you will see the latest news from the world of music and rock and roll<br>Subscribe to us for news from music inductry.</p>
  </div>
</div>

app/views/pages/sub.html.erb
<h1 class="my-4">Thanks for Subscribe!</h1>

<div class="card_x">
  <img class="card-img-top show_img" src="">
  <div class="card-body">
    <h2 class="card-title">TNK?</h2>
    <p class="card-text">We are just a team of bloggers, programmers and just rock and roll fans.<br>In our blog you will see the latest news from the world of music and rock and roll<br>Subscribe to us for news from music inductry.</p>
  </div>
</div>

app/views/posts/edit.html.erb
<h1 class="my-4">Edit Post #<%= @post.id %></h1>

<%= form_for :post, url: post_path(@post), method: :patch do |f| %>

  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger">
        <%= msg %>
      </div>
    <% end %>
  <% end %>

  <p>
    Title<br>
    <%= f.text_field(:title, {:class => "form-control"}) %>
  </p>
  <p>
    Text<br>
    <%= f.text_area(:body, {:class => "form-control"}) %>
  </p>

  <p>
    Image URL<br>
    <%= f.url_field(:image, {:class => "form-control"}) %>
  </p>
  <p>
    <%= f.submit({:class => "btn btn-success"}) %>
  </p>
<% end %>

app/views/posts/index.html.erb
<h1 class="my-4">All post's:</h1>

<% @post.each do |post| %>
<div class="card_x">
  <div class="card-white mb-4">
    <!-- Добавити Картинку через Пост -->
    <img class="card-img-top" src="<%= post.image %>">
    <div class="card-body">
      <h2 class="card-title"><%= post.title %></h2>
      <p class="card-text"><%= post.body %></p>
      <%= link_to "Read More »", post_path(post), :class => "btn btn-success" %>
    </div>
    <div class="card-footer text-muted">
      Created at : <%= post.created_at.strftime("%b %d, %Y - %k:%M %p") %>
    </div>
  </div>
</div>
<br>
<% end %>

app/views/posts/new.html.erb
<h1 class="my-3">Новий Пост</h1>

<%= form_for :post, url: posts_path do |f| %>

  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger">
        <%= msg %>
      </div>
    <% end %>
  <% end %>

  <p>
    Title<br>
    <%= f.text_field(:title, {:class => "form-control"}) %>
  </p>
  <p>
    Text<br>
    <%= f.text_area(:body, {:class => "form-control"}) %>
  </p>

  <p>
    Image URL<br>
    <%= f.url_field(:image, {:class => "form-control"}) %>
  </p>


  <p>
    <%= f.submit({:class => "btn btn-success"}) %>
  </p>
<% end %>

app/views/posts/show.html.erb
<h1 class="my-4">Post #<%= @post.id %></h1>

<div class="card_x">
  <img class="card-img-top show_img" src="<%= @post.image %>">
  <div class="card-body">
    <h2 class="card-title"><%= @post.title %></h2>
    <p class="card-text"><%= @post.body %></p>
  </div>
  <div class="card-brn">
    <%= link_to "Edit", edit_post_path(@post), :class => "btn btn-primary" %>
    <%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Хочете видалити статтю?"}, :class => "btn btn-danger" %>
  </div>
  <div class="card-footer text-muted">
    Created at : <%= @post.created_at.strftime("%b %d, %Y - %k:%M %p") %>
  </div>
</div>
<br>


<h2 class="my-3">All Comment's</h2>
<% @post.comments.each do |comment| %>
  <div class="alert alert-dark comment-block">
    <p><strong><%= comment.username %></strong>: <%= comment.body%></p>
    <p class="text-right text-muted"><%= comment.created_at.strftime("%b %d - %k:%M %p") %></p>
  </div>
<% end %>



<h2 class="my-3">Add Comment</h2>
<%= form_for([@post, @post.comments.build]) do |f| %>

  <p>
    User<br>
    <%= f.text_field(:username, {:class => "form-control"}) %>
  </p>
  <p>
    Text<br>
    <%= f.text_area(:body, {:class => "form-control"}) %>
  </p>
  <p>
    <%= f.submit("Add Comment",{:class => "btn btn-success"}) %>
  </p>
<% end %>

app/views/subscribers/new.index.erb
<h1>TEST TEST</h1>